### ISSUE TITLE
Deprecated moment.js warnings

### ISSUE THREAD

**Issue by johngeorgewright** [wanasit/chrono#56]
```
Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. https://github.com/moment/moment/issues/1779
Error:
  at deprecate node_modules/moment/moment.js:738:42)
  at node_modules/moment/moment.js:2554:37
  at hookCallback (node_modules/moment/moment.js:8:85)
  at Object.<anonymous> (node_modules/moment/moment.js:11:2)
  ...
  at Object.<anonymous> (node_modules/chrono-node/src/parsers/EN/ENISOFormatParser.js:10:14)
  ...
  at Object.<anonymous> (node_modules/chrono-node/src/options.js:1:87)
  ...
  at Object.<anonymous> (node_modules/chrono-node/src/chrono.js:2:33)
  ...
```

**Comment by wanasit** [comment]
I believed this one already been solved.
